### ISSUE TITLE
Migration to different go client

### ISSUE THREAD

**Issue by jtcarnes** [denouche/terraform-provider-awx#10]
The current go client used is currently coded by hand and has several unimplemented endpoints. There exist go clients that are generated from awx's swagger api that have the full capabilities we are looking for and are kept up to date using automation.

Repo here: https://github.com/go-limix/awx-client

This might take some work, but it would allow for the rest of the resources to be quickly added.

**Comment by denouche** [comment]
Hello @jtcarnes
Even if it's coded by hand we prefer to have the possibility to make modifications on the goawx client instead of depending on a third party projet which I don't know if it will be maintened.
I know the client and the terraform provider is not complete for now but we will add the others resources by opportunity when we will need them.
I see you already started to do so ;)
Thank you!
